name: test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Pull container
        run: docker pull maxxing/compiler-dev

      - name: Prepare container
        run: |
          docker create --name compiler-test \
          -v ${{ github.workspace }}:/root/compiler \
          maxxing/compiler-dev \
          sleep infinity

      - name: Start container
        run: docker start compiler-test

      - name: Run koopa test
        run: docker exec compiler-test autotest -koopa /root/compiler

      - name: Run riscv test
        run: docker exec compiler-test autotest -riscv /root/compiler
